# -*- coding: utf-8 -*-
"""dmmlm1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DsynVQHNcOWyJISItUOz-J6EdBscPV6K
"""

import pandas as pd

df=pd.read_csv("/content/Advertising.csv",index_col=0)

df

df.info()

X=df.drop("Sales",axis=1)
y=df["Sales"]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

X_test.shape

from sklearn.linear_model import LinearRegression

lr=LinearRegression()

lr.fit(X_train,y_train)

lr.score(X_test,y_test)



import joblib

# Save the model
joblib.dump(lr, 'linear_regression_model.pkl')
print("Model saved successfully as linear_regression_model.pkl")

